package com.github.takahirom.roborazzi

object RobolectricDeviceQualifiers {
  // Generated by [GenerateQualifiersTest.kt]
  // Data from: AOSP https://android.googlesource.com/platform/tools/base/+/mirror-goog-studio-master-dev/sdklib/src/main/java/com/android/sdklib/devices
// FROM: tv.xml
  const val AndroidTV1080p = "w7670dp-h4314dp-xlarge-long-notround-television-xhdpi-keyshidden-dpad"
  const val AndroidTV720p = "w7670dp-h4314dp-xlarge-long-notround-television-tvdpi-keyshidden-dpad"

  // FROM: devices.xml
// FROM: wear.xml
  const val WearOSSquare = "w186dp-h186dp-small-long-round-watch-hdpi-keyshidden-nonav"
  const val WearOSRound = "w213dp-h213dp-small-long-round-watch-hdpi-keyshidden-nonav"
  const val WearOSRoundChin = "w249dp-h226dp-small-notlong-notround-watch-tvdpi-keyshidden-nonav"

  // FROM: nexus.xml
  const val NexusOne = "w302dp-h503dp-normal-long-notround-any-hdpi-keyshidden-trackball"
  const val Nexus4 = "w384dp-h640dp-normal-notlong-notround-any-xhdpi-keyshidden-nonav"
  const val Nexus10 = "w1365dp-h853dp-xlarge-notlong-notround-any-xhdpi-keyshidden-nonav"
  const val Nexus7 = "w594dp-h951dp-large-notlong-notround-any-xhdpi-keyshidden-nonav"
  const val Nexus5 = "w388dp-h690dp-normal-notlong-notround-any-xxhdpi-keyshidden-nonav"
  const val Nexus6 = "w467dp-h830dp-normal-notlong-notround-any-560dpi-keyshidden-nonav"
  const val Nexus9 = "w1133dp-h850dp-xlarge-notlong-notround-any-xhdpi-keyshidden-nonav"
  const val Nexus5X = "w409dp-h724dp-normal-notlong-notround-any-420dpi-keyshidden-nonav"
  const val Nexus6P = "w428dp-h762dp-normal-notlong-notround-any-560dpi-keyshidden-nonav"
  const val PixelC = "w1329dp-h935dp-xlarge-notlong-notround-any-xhdpi-keyshidden-nonav"
  const val PixelXL = "w431dp-h766dp-normal-notlong-notround-any-560dpi-keyshidden-nonav"
  const val Pixel5 = "w390dp-h844dp-normal-long-notround-any-440dpi-keyshidden-nonav"

  // FROM: automotive.xml
  const val Automotive1024plandscape =
    "w1077dp-h808dp-normal-notlong-notround-car-mdpi-keyshidden-nonav"
}
