package com.github.takahirom.roborazzi

object RobolectricDeviceQualifiers {
  // Generated by [GenerateQualifiersTest.kt]
  // Data from: AOSP https://android.googlesource.com/platform/tools/base/+archive/refs/heads/mirror-goog-studio-main/sdklib/src/main/resources/com/android/sdklib/devices.tar.gz

	// Type: android-automotive-playstore
	const val Automotive1024plandscape = "w1024dp-h768dp-normal-notlong-notround-car-mdpi-keyshidden-nonav"

	// Type: android-desktop
	const val SmallDesktop = "w1366dp-h768dp-xlarge-long-notround-any-mdpi-keyshidden-nonav"
	const val MediumDesktop = "w1920dp-h1080dp-xlarge-long-notround-any-xhdpi-keyshidden-nonav"
	const val LargeDesktop = "w1920dp-h1080dp-xlarge-long-notround-any-mdpi-keyshidden-nonav"

	// Type: default
	const val ResizableExperimental = "w411dp-h891dp-normal-notlong-notround-any-420dpi-keyshidden-nonav"
	const val SmallPhone = "w360dp-h640dp-normal-long-notround-any-xhdpi-keyshidden-nonav"
	const val MediumPhone = "w411dp-h914dp-normal-long-notround-any-420dpi-keyshidden-nonav"
	const val MediumTablet = "w1280dp-h800dp-xlarge-notlong-notround-any-xhdpi-keyshidden-nonav"
	const val NexusOne = "w320dp-h533dp-normal-long-notround-any-hdpi-keyshidden-trackball"
	const val Nexus7 = "w600dp-h960dp-large-notlong-notround-any-xhdpi-keyshidden-nonav"
	const val Nexus9 = "w1024dp-h768dp-xlarge-notlong-notround-any-xhdpi-keyshidden-nonav"
	const val PixelC = "w1280dp-h900dp-xlarge-notlong-notround-any-xhdpi-keyshidden-nonav"
	const val PixelXL = "w411dp-h731dp-normal-notlong-notround-any-560dpi-keyshidden-nonav"
	const val Pixel4 = "w393dp-h829dp-normal-long-notround-any-440dpi-keyshidden-nonav"
	const val Pixel4XL = "w411dp-h869dp-normal-long-notround-any-560dpi-keyshidden-nonav"
	const val Pixel4a = "w393dp-h851dp-normal-long-notround-any-440dpi-keyshidden-nonav"
	const val Pixel5 = "w393dp-h851dp-normal-long-notround-any-440dpi-keyshidden-nonav"
	const val Pixel6 = "w411dp-h914dp-normal-long-notround-any-420dpi-keyshidden-nonav"
	const val Pixel6Pro = "w411dp-h891dp-normal-long-notround-any-560dpi-keyshidden-nonav"
	const val Pixel6a = "w411dp-h914dp-normal-long-notround-any-420dpi-keyshidden-nonav"
	const val Pixel7Pro = "w411dp-h891dp-normal-long-notround-any-560dpi-keyshidden-nonav"
	const val Pixel7 = "w411dp-h914dp-normal-long-notround-any-420dpi-keyshidden-nonav"

	// Type: android-tv
	const val Television4K = "w960dp-h540dp-xlarge-long-notround-television-xxxhdpi-keyshidden-dpad"
	const val Television1080p = "w960dp-h540dp-xlarge-long-notround-television-xhdpi-keyshidden-dpad"
	const val Television720p = "w962dp-h541dp-large-long-notround-television-tvdpi-keyshidden-dpad"

	// Type: android-wear
	const val WearOSLargeRound = "w227dp-h227dp-small-long-round-watch-xhdpi-keyshidden-nonav"
	const val WearOSSmallRound = "w192dp-h192dp-small-long-round-watch-xhdpi-keyshidden-nonav"
	const val WearOSRectangular = "w201dp-h238dp-small-long-notround-watch-xhdpi-keyshidden-nonav"
	const val WearOSSquare = "w180dp-h180dp-small-long-round-watch-xhdpi-keyshidden-nonav"

}